-- TerraFind Nagpur District PostgreSQL / Supabase Production Schema
-- Scope: Strictly Nagpur District, Maharashtra, India (5 Analytical Zones)
-- Core Mandate: Real Data First. Fast Search Second. UI Third. Zero Fabrication.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- PostGIS spatial support (uncomment on PostGIS-enabled environments):
-- CREATE EXTENSION IF NOT EXISTS postgis;

-- ====================================================================
-- 1. User Profiles & Authentication
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  full_name TEXT,
  avatar_url TEXT,
  phone TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own profile"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id);

-- ====================================================================
-- 2. Favorites Table
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.favorites (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  property_id TEXT NOT NULL,
  property_snapshot JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, property_id)
);

ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own favorites"
  ON public.favorites FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own favorites"
  ON public.favorites FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own favorites"
  ON public.favorites FOR DELETE
  USING (auth.uid() = user_id);

-- ====================================================================
-- 3. Dedicated Properties Table (Nagpur District Live Inventory & Staging)
-- Zero Fabrication: Missing fields are stored as NULL, never invented.
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.properties (
  id TEXT PRIMARY KEY,
  source TEXT NOT NULL,
  source_listing_id TEXT,
  source_url TEXT,
  source_type TEXT NOT NULL DEFAULT 'active_listing', -- active_listing, project, government_valuation, market_dataset, direct_submission, demo
  source_date DATE,
  is_demo BOOLEAN NOT NULL DEFAULT false,

  title TEXT NOT NULL,
  property_type TEXT NOT NULL,
  transaction_type TEXT NOT NULL DEFAULT 'sale', -- sale, rent
  bhk NUMERIC, -- NULL if not reported by source; NEVER converted to area
  bedrooms INT,
  bathrooms INT, -- NULL if not reported by source

  price NUMERIC NOT NULL,
  area_sqft NUMERIC, -- NULL if not reported by source; NEVER derived from BHK
  carpet_area_sqft NUMERIC,
  price_per_sqft NUMERIC, -- Calculated ONLY when legitimate price AND legitimate area exist

  locality TEXT NOT NULL,
  city TEXT NOT NULL DEFAULT 'Nagpur',
  district TEXT NOT NULL DEFAULT 'Nagpur',
  pincode TEXT, -- NULL if unverified; NEVER generated by zone formula
  address TEXT, -- Original source address or NULL; NEVER constructed from locality name
  zone TEXT NOT NULL, -- east, north, west, south, centre
  latitude DOUBLE PRECISION, -- Exact property latitude ONLY; NULL if unverified
  longitude DOUBLE PRECISION, -- Exact property longitude ONLY; NULL if unverified
  locality_latitude DOUBLE PRECISION, -- Locality-level centroid reference
  locality_longitude DOUBLE PRECISION,

  project_name TEXT,
  society_name TEXT,
  builder_name TEXT,
  listing_agent TEXT,
  listing_agent_contact TEXT,

  floor INT,
  total_floors INT,
  furnishing TEXT,
  parking TEXT,
  amenities_json JSONB DEFAULT '[]'::jsonb, -- Property-source amenities only; never hardcoded

  -- Section 43: Real Source Images
  primary_image_url TEXT, -- NULL when source has no photo; UI shows honest 'Photo unavailable'
  image_urls JSONB DEFAULT '[]'::jsonb,
  image_source TEXT,
  image_retrieved_at TIMESTAMPTZ,
  image_status TEXT DEFAULT 'pending', -- pending, available, unavailable, verified

  status TEXT NOT NULL DEFAULT 'active', -- active, inactive, sold, reported_active_on_source
  approval_status TEXT NOT NULL DEFAULT 'approved',
  listed_date TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  imported_at TIMESTAMPTZ DEFAULT NOW(),
  data_quality_note TEXT
);

-- Essential & Composite Indexes for High Performance (Section 26 & 33)
CREATE INDEX IF NOT EXISTS idx_properties_district ON public.properties(district);
CREATE INDEX IF NOT EXISTS idx_properties_zone ON public.properties(zone);
CREATE INDEX IF NOT EXISTS idx_properties_locality ON public.properties(locality);
CREATE INDEX IF NOT EXISTS idx_properties_status ON public.properties(status);
CREATE INDEX IF NOT EXISTS idx_properties_source_type ON public.properties(source_type);
CREATE INDEX IF NOT EXISTS idx_properties_property_type ON public.properties(property_type);
CREATE INDEX IF NOT EXISTS idx_properties_bhk ON public.properties(bhk);
CREATE INDEX IF NOT EXISTS idx_properties_price ON public.properties(price);
CREATE INDEX IF NOT EXISTS idx_properties_price_per_sqft ON public.properties(price_per_sqft);
CREATE INDEX IF NOT EXISTS idx_properties_pincode ON public.properties(pincode);
CREATE INDEX IF NOT EXISTS idx_properties_is_demo ON public.properties(is_demo);
CREATE INDEX IF NOT EXISTS idx_properties_retrieved_at ON public.properties(imported_at);

-- Composite Indexes
CREATE INDEX IF NOT EXISTS idx_props_dist_zone_status ON public.properties(district, zone, status);
CREATE INDEX IF NOT EXISTS idx_props_dist_zone_price ON public.properties(district, zone, price);
CREATE INDEX IF NOT EXISTS idx_props_dist_loc_status ON public.properties(district, locality, status);
CREATE INDEX IF NOT EXISTS idx_props_dist_zone_bhk_price ON public.properties(district, zone, bhk, price);

-- ====================================================================
-- 4. Property Images Table (Section 43.1 - Normalized Multiple Images)
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.property_images (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  property_id TEXT NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  source TEXT NOT NULL,
  source_image_id TEXT,
  sort_order INT DEFAULT 0,
  is_primary BOOLEAN DEFAULT false,
  license TEXT,
  retrieved_at TIMESTAMPTZ DEFAULT NOW(),
  status TEXT DEFAULT 'active'
);

CREATE INDEX IF NOT EXISTS idx_property_images_prop_id ON public.property_images(property_id);

-- ====================================================================
-- 5. RERA Projects Table (Section 7 - Strictly Separated from Active Listings)
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.rera_projects (
  project_id TEXT PRIMARY KEY,
  rera_number TEXT NOT NULL UNIQUE,
  project_name TEXT NOT NULL,
  promoter TEXT NOT NULL,
  project_type TEXT NOT NULL,
  locality TEXT NOT NULL,
  city TEXT NOT NULL DEFAULT 'Nagpur',
  district TEXT NOT NULL DEFAULT 'Nagpur',
  zone TEXT,
  registration_date DATE,
  completion_date DATE,
  status TEXT NOT NULL,
  buildings INT,
  units INT,
  source TEXT NOT NULL DEFAULT 'MahaRERA Project Registry',
  source_url TEXT DEFAULT 'https://maharerait.mahaonline.gov.in',
  source_record_id TEXT,
  retrieved_at TIMESTAMPTZ DEFAULT NOW(),
  data_year INT,
  quality_status TEXT NOT NULL DEFAULT 'official_statutory_filing',
  validation_notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_rera_projects_district ON public.rera_projects(district);
CREATE INDEX IF NOT EXISTS idx_rera_projects_locality ON public.rera_projects(locality);
CREATE INDEX IF NOT EXISTS idx_rera_projects_zone ON public.rera_projects(zone);

-- ====================================================================
-- 6. RERA Updates Table (Section 7 & 12 - Historical Status Changes)
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.rera_updates (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  rera_number TEXT NOT NULL REFERENCES public.rera_projects(rera_number) ON DELETE CASCADE,
  previous_status TEXT,
  new_status TEXT NOT NULL,
  completion_date_revised DATE,
  update_date DATE NOT NULL,
  notes TEXT,
  recorded_at TIMESTAMPTZ DEFAULT NOW()
);

-- ====================================================================
-- 7. Historical Property Observations Table (Section 12 - Append-Only)
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.property_observations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  property_id TEXT,
  source TEXT NOT NULL,
  source_listing_id TEXT,
  observation_date DATE NOT NULL,
  price NUMERIC,
  price_per_sqft NUMERIC,
  status TEXT,
  retrieved_at TIMESTAMPTZ DEFAULT NOW(),
  notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_prop_obs_prop_id ON public.property_observations(property_id);
CREATE INDEX IF NOT EXISTS idx_prop_obs_date ON public.property_observations(observation_date);

-- ====================================================================
-- 8. Market Observations & Locality Benchmarks (Section 13 & 21)
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.market_observations (
  observation_id TEXT PRIMARY KEY,
  district TEXT NOT NULL DEFAULT 'Nagpur',
  zone TEXT NOT NULL,
  locality TEXT NOT NULL,
  property_type TEXT,
  metric TEXT NOT NULL, -- average_price_per_sqft, median_price, transaction_volume
  value NUMERIC NOT NULL,
  unit TEXT NOT NULL,
  period_start DATE,
  period_end DATE,
  data_year INT,
  sample_size INT,
  source TEXT NOT NULL,
  source_url TEXT,
  geographic_scope TEXT,
  quality_status TEXT NOT NULL,
  calculation_method TEXT,
  recorded_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_market_obs_zone_loc ON public.market_observations(zone, locality);
CREATE INDEX IF NOT EXISTS idx_market_obs_year ON public.market_observations(data_year);

-- ====================================================================
-- 9. Government Valuations Table (Section 22 - IGR / e-ASR Annual Ready Reckoner)
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.government_valuations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  district TEXT NOT NULL DEFAULT 'Nagpur',
  zone TEXT NOT NULL,
  village_or_locality TEXT NOT NULL,
  survey_number TEXT,
  property_type TEXT NOT NULL, -- land, residential_flat, commercial
  asr_rate_per_sqm NUMERIC NOT NULL,
  asr_rate_per_sqft NUMERIC,
  effective_year INT NOT NULL,
  source TEXT NOT NULL DEFAULT 'Maharashtra IGR / e-ASR',
  source_url TEXT DEFAULT 'https://igrmaharashtra.gov.in',
  retrieved_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(district, village_or_locality, property_type, effective_year)
);

-- ====================================================================
-- 10. Rejected Records Pipeline Table (Section 9 - Preserve all rejections)
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.rejected_records (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  source_record_id TEXT NOT NULL,
  source TEXT NOT NULL,
  source_url TEXT,
  locality TEXT,
  city TEXT,
  property_type TEXT,
  raw_price NUMERIC,
  rejection_category TEXT NOT NULL, -- price_outlier_token, price_outlier_extreme, geographic_scope_violation, missing_mandatory_fields, invalid_property_type, duplicate_record, test_record
  rejection_reason TEXT NOT NULL,
  rejected_at TIMESTAMPTZ DEFAULT NOW()
);

-- ====================================================================
-- 11. AI Evidence Cache Table (Section 29 - Source Grounding)
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.ai_evidence (
  evidence_id TEXT PRIMARY KEY,
  entity_type TEXT NOT NULL, -- locality, property, zone
  entity_id TEXT NOT NULL,
  metric TEXT NOT NULL,
  value JSONB NOT NULL,
  unit TEXT,
  period_start DATE,
  period_end DATE,
  geographic_scope TEXT NOT NULL,
  source TEXT NOT NULL,
  source_url TEXT,
  source_date DATE,
  retrieved_at TIMESTAMPTZ DEFAULT NOW(),
  quality_status TEXT NOT NULL,
  calculation_method TEXT,
  notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_ai_evidence_entity ON public.ai_evidence(entity_type, entity_id);

-- ====================================================================
-- 12. Localities and Analytical Zones Reference
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.zones (
  id TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  slug TEXT NOT NULL,
  description TEXT,
  center_lat DOUBLE PRECISION NOT NULL,
  center_lon DOUBLE PRECISION NOT NULL,
  bounds JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS public.localities (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  zone_id TEXT REFERENCES public.zones(id),
  district TEXT NOT NULL DEFAULT 'Nagpur',
  pincode TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  UNIQUE(district, name)
);

-- ====================================================================
-- 13. Location Intelligence Overlays
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.air_quality_observations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  us_aqi INT NOT NULL,
  european_aqi INT,
  pm2_5 NUMERIC,
  pm10 NUMERIC,
  source TEXT NOT NULL DEFAULT 'Open-Meteo Air Quality API',
  observed_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.safety_statistics (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  district TEXT NOT NULL DEFAULT 'Nagpur',
  commissionerate TEXT NOT NULL DEFAULT 'Nagpur Police Commissionerate',
  cognizable_crimes INT NOT NULL,
  crime_rate_per_lakh NUMERIC NOT NULL,
  reporting_level TEXT NOT NULL DEFAULT 'Commissionerate / District Level',
  year INT NOT NULL,
  source TEXT NOT NULL DEFAULT 'NCRB / Nagpur Police Commissionerate',
  published_url TEXT,
  UNIQUE(district, year)
);
